service: serverless-typescript

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-1
  profile: rayhan

# functions
functions:
  product_list:
    handler: src/functions/products.index
    events:
      - http:
          path: products
          method: get
          cors: true
  product_details:
    handler: src/functions/products.show
    events:
      - http:
          path: products/{id}
          method: get
          cors: true
# Serverless plugins
plugins:
  - serverless-plugin-typescript
  - serverless-offline
# Resources your functions use
# resources:
#   Resources:
#     # SNS Topics
#     SNSHelloEvent:
#       Type: AWS::SNS::Topic
#       Properties:
#         DisplayName: Hello Event Topic
#         TopicName: hello-event
